language: python
python:
  - "3.7"
  - "3.8"
before_install:
  - sudo apt update
  - sudo apt install libxslt-dev libxml2-dev
install:
  - pip install -r requirements.txt
script:
  - pytest test/event_unittest.py test/event_b_unittest.py test/schedule_unittest.py
